### ISSUE TITLE
swig/_mapper.so not linked to libmapper-0.so.2

### ISSUE THREAD

**Issue by husk00** [radarsat1/webmapper#4]
Hi,
thanks for this software. I compiled succefully libmapper (test.py worked properly). Trying webmapper I get this error:

 _mod = imp.load_module('_mapper', fp, pathname, description)
ImportError: libmapper-0.so.2: cannot open shared object file: No such file or directory

ldd to _mapper.so:
        linux-vdso.so.1 =>  (0x00007fff0f9fe000)
    libmapper-0.so.2 => not found
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0a90ae8000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0a90722000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f0a90f50000)

I'm on linux ubuntu x64 with kernel 3.18.
What I'm doing wrong?

**Comment by radarsat1** [comment]
You've got to ensure that _mapper.so can find libmapper-0.so.  Try installing libmapper to a library directory on the PATH (e.g. /usr/lib) or putting it in the same folder as _mapper.so.  If ldd can find it then things should work smoothly.

**Comment by husk00** [comment]
I had to manually copy libmapper-0.so\* in /usr/lib.
Then every thing worked as expected.

thanks

**Comment by radarsat1** [comment]
Great! In general so files must be accessible via ld.so.conf.  You can configure /etc/ld.so.conf.d/ to point to a location where you installed libmapper.  webmapper assumes that libmapper has been compiled and installed correctly.  This will be less confusing on systems that include a libmapper package.
