### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by CJunit** [radarsat1/webmapper#5]
It's been a struggle so far. Got liblo compiled and detected, libmapper compiled, tested, and installed. At first I had the same problem as #4 in that libmapper was not seen in /usr/local/lib, so I created links in /usr/lib. Then I had to install netifaces. Now what I get is:

$ ./webmapper.py
serving at port 50000
[ws] [Errno 32] Broken pipe
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51016)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

****

I have no idea what it means, but it feels like I am getting closer to having it working. It opens a bare mapperGUI in my browser. I am running KDE neon 5.13.4/18.04

**Comment by CJunit** [comment]
After installing Chromium and playing with the mapper object and helpfile in Pd it seems to be mostly working, I see my Pd names/nodes in only the List view, but it's a start.

It looks like I should have posted at the /libmapper/webmapper project!

**Comment by radarsat1** [comment]
Ah, yeah, I started the project here but it since moved to the libmapper project.  Do post over there if you have further problems!  I just enabled issues on it.
